---
- name: Copy repo file
  copy:
    src: internal.repo
    dest: /etc/yum.repos.d/internal.repo

- name: install HAProxy
  yum:
    name: haproxy 
    state: latest

- name: start and enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: HAproxy_restart
